const savedStates = [
  {
    game: {
      players: ['adam', 'cindy', 'david', 'edgar', 'fred'],
      roles: {},
      started: false,
      host: null,
      policies: [],
      discards: [],
      government: { president: null, chancellor: null },
      governmentApproved: false,
      events: [],
      presidentHasChosen: false,
      policyChoices: [],
      enactedPolicies: [],
      gameOver: false,
      presidentShouldInvestigate: false,
      presidentShouldKill: false,
      presidentShouldViewPolicies: false,
      vetoAvailable: false,
      chancellorHasVetoed: false,
      presidentRejectedVeto: false,
      lastPresident: null,
      lastChancellor: null,
    },
    description: 'initial',
  },
  {
    game: {
      gameOver: false,
      presidentHasChosen: false,
      presidentShouldKill: false,
      players: ['adam', 'cindy', 'david', 'edgar', 'fred', 'testhost'],
      roles: {},
      policies: [],
      lastUpdate: { seconds: 1600421936, nanoseconds: 286000000 },
      events: ['Game created. Code: eye'],
      lastPresident: null,
      presidentShouldInvestigate: false,
      chancellorHasVetoed: false,
      vetoAvailable: false,
      host: 'testhost',
      government: { chancellor: null, president: null },
      enactedPolicies: [],
      discards: [],
      lastChancellor: null,
      started: false,
      code: 'eye',
      presidentRejectedVeto: false,
      governmentApproved: false,
      presidentShouldViewPolicies: false,
      policyChoices: [],
    },
  },
  {
    description: 'game started',
    game: {
      gameOver: false,
      government: { chancellor: null, president: null },
      discards: [],
      lastPresident: null,
      policies: [
        'RED',
        'RED',
        'RED',
        'RED',
        'BLUE',
        'RED',
        'BLUE',
        'RED',
        'BLUE',
        'BLUE',
        'RED',
        'RED',
        'BLUE',
        'RED',
        'RED',
        'RED',
        'BLUE',
      ],
      lastUpdate: { seconds: 1600422001, nanoseconds: 831000000 },
      code: 'eye',
      policyChoices: [],
      events: ['Game created. Code: eye', 'Game has started'],
      presidentShouldInvestigate: false,
      enactedPolicies: [],
      host: 'testhost',
      started: true,
      roles: {
        edgar: 'blue',
        adam: 'redLeader',
        david: 'red',
        testhost: 'blue',
        fred: 'blue',
        cindy: 'blue',
      },
      presidentShouldViewPolicies: false,
      players: ['adam', 'cindy', 'david', 'edgar', 'fred', 'testhost'],
      presidentHasChosen: false,
      governmentApproved: false,
      lastChancellor: null,
      presidentShouldKill: false,
      presidentRejectedVeto: false,
      vetoAvailable: false,
      chancellorHasVetoed: false,
    },
  },
  {
    game: {},
    description: '',
  },
  {
    game: {},
    description: '',
  },
  {
    game: {},
    description: '',
  },
]
